SELECT BOOK.AUTHOR_ID , AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK JOIN AUTHOR  ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
          JOIN BOOK_SALES ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE YEAR(BOOK_SALES.SALES_DATE) = 2022 AND MONTH(BOOK_SALES.SALES_DATE) = 1
GROUP BY BOOK.CATEGORY,BOOK.AUTHOR_ID
ORDER BY BOOK.AUTHOR_ID , BOOK.CATEGORY DESC